"""Измененное модели сообщение 

Revision ID: 0a5626c1143d
Revises: 3f5f7f69319a
Create Date: 2024-12-21 05:54:48.026622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5626c1143d'
down_revision = '3f5f7f69319a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_call', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('tool_call')

    # ### end Alembic commands ###
