"""Контрольная миграция 2

Revision ID: 2f3805f3839f
Revises: 0a5626c1143d
Create Date: 2024-12-23 06:03:58.024229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2f3805f3839f'
down_revision = '0a5626c1143d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)

    # ### end Alembic commands ###
