"""Измененное модели сообщение 

Revision ID: 3f5f7f69319a
Revises: ca084d3122fd
Create Date: 2024-12-21 05:48:51.568961

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f5f7f69319a'
down_revision = 'ca084d3122fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tool_call_id', sa.String(length=50), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=15), nullable=True))
        batch_op.drop_column('tool_call_id')

    # ### end Alembic commands ###
